### ISSUE TITLE
Update all references to s3 stemcells to new url

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf-docs#111]
Looks like the stemcell URLs are changing https://github.com/cloudfoundry/bootstrap-cf-plugin/commit/86ab7928c1650c1f575d93462eeae8ba70d83865:

``` diff
-      DEFAULT_LIGHT_STEMCELL_URL = "http://bosh-jenkins-artifacts.s3.amazonaws.com/last_successful_bosh-stemcell-aws_light.tgz"
+      DEFAULT_LIGHT_STEMCELL_URL = "http://bosh-jenkins-artifacts.s3.amazonaws.com/bosh-stemcell/aws/latest-light-bosh-stemcell-aws.tgz"
```

**Comment by jfoley** [comment]
@tsaleh - who owns updating these docs?

@aramprice / @jfoley

**Comment by tammersaleh** [comment]
I'm honestly not sure.  @jbayer seems to be active in that repo...

**Comment by tammersaleh** [comment]
@drnic if you make this a PR, I'm sure we'll pull it in quickly.

**Comment by drnic** [comment]
Yeah I think I can now generate the latest URLs with that fancy script I put on bosh-users (from tracker).

```
--
```

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic

**Comment by jbayer** [comment]
@drnic does can you suggest the right updates for the docs then? @mpmcgarry works on the docs.

**Comment by mmb** [comment]
The cloudfoundry docs have been updated:
https://github.com/cloudfoundry/cf-docs/commit/2ea6b123a37e775a33d23f0c29c82fc9276c8744

They will be included in the next push. 

@mmb / @matthewmcnew
