### ISSUE TITLE
BOSH job monit file can be empty

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry-attic/cf-docs#149]
From: https://github.com/cloudfoundry/bosh/issues/293 and @msackman

Bosh currently doesn't allow you to have a jobless release. This is very annoying as you're initially developing a release where all you care about is getting things compiled, and forces you to invent phantom jobs which wastes time.

That said, it's also very useful to have a job onto which your packages are deployed so that you can inspect your progress. In the end I created a phantom job which bosh/monit was happy with, however, I've just discovered by trial and error that having an empty monit file works and does not upset bosh or monit (which perhaps makes a mockery of the error you get if you have no monit file at all). This should mentioned in the documentation(!) and in the inevitable (and much needed) tutorials on how to develop a bosh release.

There should perhaps also be a built-in "deploy-all" job that simply finds every package in the release and depends on them all.

**Comment by mmb** [comment]
See comments from @tsaleh in https://github.com/cloudfoundry/bosh/issues/293

@mmb / @matthewmcnew

**Comment by jbayer** [comment]
i originally opened this issue in response to that @tsaleh comment. this issue is a reminder that we need to document this.

**Comment by adamstegman** [comment]
@araher @kimahoff @animatedmax Do you want to create a story for this, or recreate it against the docs-bosh repository?

CF Community Pair (@adamstegman & @mbhave)

**Comment by animatedmax** [comment]
I created a story for this:
https://www.pivotaltracker.com/story/show/70776144

Thanks!

**Comment by adamstegman** [comment]
We are closing this issue since there is a story for this in the new docs.

Thanks,
CF Community Pair (@adamstegman & @mbhave)
