### ISSUE TITLE
warden doc isn't linked to home

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf-docs#156]
http://docs.cloudfoundry.com/docs/running/architecture/warden.html isn't linked to the home page of docs

**Comment by scottfrederick** [comment]
Do you mean that page isn't linked from http://docs.cloudfoundry.com? None of the individual CF component pages are linked from there. In the "Running CF" column there is 

 Understanding the Architecture
 [A Tour of Each Component](http://docs.cloudfoundry.com/docs/running/architecture/)

The "Tour" page in turn links to all the component pages. Linking each component page from the home page would make for a very busy home page.

**Comment by drnic** [comment]
Ok. I mentioned it because there were other Warden articles linked on the home page of the docs.
