### ISSUE TITLE
node-service-bindings missing critical information

### ISSUE THREAD

**Issue by freethejazz** [cloudfoundry-attic/cf-docs#176]
The note at the top of the node-service-binding doc states:

> Note: The auto-configuration functionality described on this page is not yet supported in Cloud Foundry v2.

but there is no information on how to manually configure services while we wait for auto-configuration to catch up.

How are node developers supposed to use services in V2?

**Comment by andypiper** [comment]
Right now, you can read the VCAP_SERVICES and other environment variables, until the relevant node modules are updated. Thanks for the feedback, we should make this more clear.

**Comment by adamstegman** [comment]
This has been fixed in the new docs: http://docs.cloudfoundry.org/buildpacks/node/node-service-bindings.html.

For any other issues, please open an issue against the new repository: https://github.com/cloudfoundry/docs-buildpacks.

Thanks,
CF Community Pair (@adamstegman & @mbhave)
