### ISSUE TITLE
Update location of stemcell

### ISSUE THREAD

**Issue by iwinoto** [cloudfoundry-attic/cf-docs#183]
The location of stemcell is no longed as documented.
To get latest stemcell for bosh/openstack, :

```
$ wget http://bosh-jenkins-artifacts.s3.amazonaws.com/bosh-stemcell/openstack/bosh-stemcell-latest-openstack-kvm-ubuntu.tgz
```

**Comment by mmb** [comment]
Fixed in commit https://github.com/cloudfoundry/cf-docs/commit/2ea6b123a37e775a33d23f0c29c82fc9276c8744

@mmb / @matthewmcnew
