### ISSUE TITLE
cf-autoconfig gem should not be used

### ISSUE THREAD

**Issue by bbuchalter** [cloudfoundry-attic/cf-docs#194]
We encountered an issue while deploying a CF app and opened a ticket (http://support.cloudfoundry.com/requests/103381) in which we were told not to use the cf-autocnfig Ruby gem. We were directed to use this gem in the docs; it sounds like it should be removed. If you need further information, let us know.

**Comment by adamstegman** [comment]
@bbuchalter This docs repo is now replaced by [docs-book-cloudfoundry](https://github.com/cloudfoundry/docs-book-cloudfoundry), so we are closing this issue.

If this still needs to be fixed, please log an issue there.

Thanks,
CF Community Pair (@adamstegman & @mbhave)
