### ISSUE TITLE
Take down any mention of micro cloud foundry

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry-attic/cf-docs#200]
Micro cloud foundry is no longer available, yet the existence of pages such as this lead users to take steps to get one.  If there is valuable content on these pages it needs to be harvested and put someplace else and we need to remove all mentions of micro cloud foundry (except maybe to say that it is no longer and maybe point people to bosh lite).

**Comment by andypiper** [comment]
Good plan. +1

**Comment by mpmcgarry** [comment]
I believe I removed all references to Micro CF.  If you notice any I
missed, lemme know.

m

**Comment by cdavisafc** [comment]
Found a few more:

http://www.cloudfoundry.com/faq
http://docs.cloudfoundry.com/docs/running/

And I filed this issue last week after someone emailed me about getting their account approved so they could use micro - at the time I thought I found a page that still described micro CF but now I can't find it.  

Also, probably not a doc issue (but rather a website issue), 

http://www.cloudfoundry.com/use

**Comment by mpmcgarry** [comment]
commented in the issue.

**Comment by mpmcgarry** [comment]
thx, btw.

**Comment by jimmida** [comment]
story in the backlog
