### ISSUE TITLE
BOSH Agent will run a hook script after a job installation is completed, but it's missed in Doc

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry-attic/cf-docs#210]
Here docs/running/bosh/reference/jobs.html.md mentioned the “prepare" script, but didn't mention the "post_install" script which gets invoked after BOSH Agent installs the job.  This script might be very helpful for some cases which need to do some post install work.

Here is the implementation: https://github.com/cloudfoundry/bosh/blob/master/bosh_agent/lib/bosh_agent/apply_plan/job.rb#L145

**Comment by adamstegman** [comment]
@JimmyMa This repository is now deprecated and replaced by [docs-book-cloudfoundry](https://github.com/cloudfoundry/docs-book-cloudfoundry).

We have reopened this issue against the new [BOSH docs repository](https://github.com/cloudfoundry/docs-bosh). We are closing this issue, see [cloudfoundry/docs-bosh#9](https://github.com/cloudfoundry/docs-bosh/issues/9) for further updates.

Thanks,
CF Community Pair (@adamstegman & @mbhave)
