### ISSUE TITLE
document how the .profile.d directory is used for pushed applications

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry-attic/cf-docs#213]
I'm not sure where in the doc set to put it, but we have an entirely undocumented feature that seems to be essentially the same as what is described here: https://devcenter.heroku.com/articles/profiled.  I've tried following this guidance from the heroku docs and it looks like it works fine.  We need to include this as well.

**Comment by adamstegman** [comment]
We have moved this to the new docs repo ([cloudfoundry/docs-dev-guide#18](https://github.com/cloudfoundry/docs-dev-guide/issues/18)) so we are closing this issue.

CF Community Pair (@adamstegman & @mbhave)
