### ISSUE TITLE
Apps#delete missing recursive parameter documentation

### ISSUE THREAD

**Issue by buddhistpirate** [cloudfoundry-attic/cf-docs#239]
The `recursive` parameter needs to be set to `true` to delete apps with service bindings. This should be documented in [source/docs/reference/cc-api.html.md](https://github.com/cloudfoundry/cf-docs/blob/master/source/docs/reference/cc-api.html.md).

**Comment by adamstegman** [comment]
@buddhistpirate This repo is now deprecated and replaced by https://github.com/cloudfoundry/docs-book-cloudfoundry. We no longer maintain this documentation, so we are closing this issue.

Thanks,
CF Community Pair (@adamstegman & @mbhave)
