### ISSUE TITLE
unescaped underscores on some pages

### ISSUE THREAD

**Issue by xchoi** [cloudfoundry-attic/cf-docs#260]
found an example here:

http://docs.cloudfoundry.com/docs/reference/cc-api.html

quota_definition_guid
quota_definition_url

are partially italicized, when in fact there should just be underscores, those should probably look like

quota_definition_guid
quota_definition_url

in the md.

![screen shot 2014-01-08 at 10 38 58 am](https://f.cloud.github.com/assets/131090/1871255/376bf8cc-7894-11e3-84c7-c452f122ac1e.png)

**Comment by animatedmax** [comment]
Hi Alex,

Thanks for pointing out this issue. They should all now be fixed.

Max
