### ISSUE TITLE
deploying cf on vcloud documentation is outdated

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-attic/cf-docs#271]
When trying to follow documentation at [1], it fails during bosh_deployer install:

```
$ >    gem install bosh_deployer
    ERROR:  While executing gem ... (Gem::DependencyResolutionError)
        conflicting dependencies aws-sdk (= 1.8.5) and aws-sdk (~> 1.3.6)
      Activated aws-sdk-1.3.6 via:
        aws-sdk-1.3.6 (~> 1.3.6), bosh_aws_registry-0.2.2 (~> 0.2.2), bosh_deployer-1.4.1 (= 1.4.1)
      instead of (= 1.8.5) via:
        blobstore_client-1.1761.0 (~> 1.1761.0), bosh_cli-1.1761.0 (>= 1.0.2), bosh_deployer-1.4.1 (= 1.4.1)
```

[1] http://docs.cloudfoundry.com/docs/running/deploying-cf/vcloud/deploying_to_vcloud_director.html

Applying the vsphere documentation worked fine on vCD 5.1 to perform bosh_micro installation.

**Comment by jbayer** [comment]
@gberche-orange just out of curiosity are you working with https://github.com/vchs/bosh_vcloud_cpi ? /cc @Justin-Yu @killian

**Comment by gberche-orange** [comment]
@jbayer thanks for the reminder. I had seen [your kind pointer on bosh-users@](https://groups.google.com/a/cloudfoundry.org/d/msg/bosh-users/xa_B8GIbEDc/kJh-8SRmSuYJ) a while ago, but was not sure whether it has been integrated into bosh gem dependencies. 

It seems not, (bosh_deployer)[https://rubygems.org/gems/bosh_deployer] and (bosh_cli_plugin_micro)[https://rubygems.org/gems/bosh_cli_plugin_micro] still (seems to lock "bosh_vcloud_cpi ~> 0.4.9"), therefore preventing 0.5.x from https://github.com/vchs/bosh_vcloud_cpi to being used.

Resulting version from use of bosh_cli_plugin_micro:

```
[gberche@bosh-cli micro01]$ gem list -d -a bosh_vcloud_cpi

*** LOCAL GEMS ***

bosh_vcloud_cpi (0.4.9)
    Author: VMware
    Homepage: http://www.vmware.com
    Installed at: /opt/rh/ruby193/root/usr/local/share/gems

    BOSH vCloud CPI
[gberche@bosh-cli micro01]$ gem list -d -a -r bosh_vcloud_cpi

*** REMOTE GEMS ***

bosh_vcloud_cpi (0.5.0, 0.4.9, 0.4.8)
    Author: VMware
    Homepage: https://github.com/vchs/bosh_vcloud_cpi

    BOSH vCloud CPI
```

@Justin-Yu is there more up-to-date documentation on use of bosh_vcloud_cpi from vchs ? Would I have to force dependencies in the gem install command ?

Likewise, it does not seem that bosh_vcloud_cpi versions are automatically pushed on rubygem.org: [version 0.5.1](https://github.com/vchs/bosh_vcloud_cpi/commit/d8dfb8e0139d01d59bc36fa0d9e0e02e064ce702) bumped 9 days ago does not seem live on rubygems.org. Could not see either public ci on travis. 

Anything that could be done to better fit the "it just works tm" cloudfoundry experience for vCloud Cf admins ?

**Comment by jbayer** [comment]
received an update from @Justin-Yu team.

```
a headsup that we have a few PRs that we'll send your way this week before the doc update
1) Update to the vcloud cpi gem used by bosh. We just getting ready to publish a new version of the gem that has changes that we need for vchs.
2) stemcell builder change to build a bespoke vcloud stemcell. We'll publish the vcloud stemcell in a VMware S3 bucket.
3) the doc update to fix for both vcloud and vchs.
```

**Comment by gberche-orange** [comment]
Thanks @Justin-Yu. What differences would there have in the vcloud stemcell w.r.t. to the vspheres ones ? The doc currently says the vcloud_cpi supports the vsphere stemcells should I wait for your vcloud stemcell ?

**Comment by gberche-orange** [comment]
Also @Justin-Yu any chances the vcloud stemcell gets uploaded to the standard S3 http://bosh-jenkins-artifacts.s3.amazonaws.com/bosh-stemcell buckets instead of a vmware specific one as I understand your post? https://groups.google.com/a/cloudfoundry.org/d/msg/bosh-dev/6dmkY_f5uW8/0znUtHae4SQJ describes the stemcell uniformization ?

**Comment by bsiravara** [comment]
@gberche-orange we will upload the stemcell to a specific S3 bucket to start with. I'll look through the post and see if we can change it next. We just finished steps 1&2 that @jbayer mentioned. Doc update coming next.

**Comment by adamstegman** [comment]
@gberche-orange Since we no longer recommend bosh_deployer, we are closing this pull request. The docs for deploying Cloud Foundry on vCloud are now [here](http://docs.cloudfoundry.org/deploying/vcloud/).

Thanks,
CF Community Pair (@adamstegman & @jtuchscherer)
