### ISSUE TITLE
cf-docs building does not detect broken local markdown hrefs 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-attic/cf-docs#276]
It would be great if cf-docs would build (e.g. on travis-ci) and would detect broken markdown hrefs, at least local references, and possibly reject PRs/commits with broken links.

I inadvertandly introduced a broken link in https://github.com/cloudfoundry/cf-docs/commit/c33c2824ac6515ca1878dd0b7dc6affef0c4a121 sorry.

Other refactorings such as renaming a page will likely introduce other similar regressions.

**Comment by testobsessed** [comment]
Hi gberche-orange! Thank you very much for reporting this issue.

We are in the process of changing how we product documentation for Cloud Foundry. You can find out more on the mail list posting here: https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/QvuoqUKekuc

As part of that change, we now have our docs generation process running on CI, so nothing makes it to our staging site without passing a link checker. The bad news is that the link checker currently cannot detect broken anchor links inside a doc. We have a story in our backlog to fix that, but it will probably be at least several weeks before we are able to add that capability.

**Comment by testobsessed** [comment]
I'm thrilled to report that our new docs toolchain (https://github.com/pivotal-cf/docs-bookbinder) reports both broken links and broken anchors now. Closing.

**Comment by gberche-orange** [comment]
Great, thanks @testobsessed !
