### ISSUE TITLE
Interest in Loggregator?

### ISSUE THREAD

**Issue by benjsmi** [cloudfoundry-attic/cf-docs#281]
Is there any interest in having the example bosh deployment manifest include loggregator and loggregator/trafficcontroller?

**Comment by adamstegman** [comment]
@programsam The [Cloud Foundry deployment docs](http://docs.cloudfoundry.org/deploying/ec2/bootstrap-aws-vpc.html) just use the existing spiff templates to generate the manifest, which include loggregator and traffic controller. Thus, we are closing this issue.

As a side note, the docs team deprecated this repo and is now working off of [this](https://github.com/cloudfoundry/docs-book-cloudfoundry) repository.

CF Community Pair (@adamstegman & @jtuchscherer)
