### ISSUE TITLE
Build Tools doc is missing `org` and `space` settings for Maven

### ISSUE THREAD

**Issue by pivotal-puma** [cloudfoundry-attic/cf-docs#284]
When we tried to use the Maven plugin as documented we got the following error message:

```
[ERROR] Failed to execute goal org.cloudfoundry:cf-maven-plugin:1.0.0:push (default-cli) on project REDACTED: An exception was caught while executing Mojo. The org is not set. -> [Help 1]
```

Once we provide `org` we get the same message for `space`. So it seems these two parameters are required.

**Comment by kimahoff** [comment]
Hi pivotal-puma,

We are in the process of moving to a new and improved open source docs site. The site isn't live yet, but you can see this fix and the updated Build Tool Integration doc here: https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/build-tool-int.html.md.erb

You can also see the topic live in our GoPivotal docs: 
http://docs.gopivotal.com/pivotalcf/devguide/deploy-apps/build-tool-int.html

Thanks for your feedback!
