### ISSUE TITLE
docs for openstack deployment are really out of date

### ISSUE THREAD

**Issue by soudmaijer** [cloudfoundry-attic/cf-docs#299]
http://docs-cloudfoundry-staging.cfapps.io/deploying/openstack/install_cf_openstack.html

I pressed the link that the docs are not working anymore, so here is the ticket :-)

**Comment by jfoley** [comment]
@soudmaijer 

Thanks for raising this issue, but this repo has been deprecated so we are going to close it. That being said, the docs around deploying to openstack are still out of date (although the docs team will be getting to it eventually) so if you would like to reopen the issue, https://github.com/cloudfoundry/docs-deploying-cf should be the appropriate place for it.

Thanks,
CF Community Pair (@jfoley & @jtuchscherer)
