### ISSUE TITLE
How did ~/workspace/bosh/boshawsbootstrap/templates/awsconfigurationtemplate.yml.erb come to existence?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf-docs#59]
In the tutorial on deploying CF on VPC it mentions editing `~/workspace/bosh/bosh_aws_bootstrap/templates/aws_configuration_template.yml.erb`; but we aren't told where that file comes from.

Perhaps should bosh_aws_bootstrap be added into the Gemfile (from git source) and then run `bundle package --all`? Testing that now.

**Comment by drnic** [comment]
I added the following to my Gemfile:

``` ruby
git "git://github.com/cloudfoundry/bosh" do
  gem "bosh_aws_bootstrap"
end
```

And ran:

```
bundle install
bundle package --all
```

And the config file can now be edited via textmate with:

```
mate vendor/cache/bosh-*/bosh_aws_bootstrap/templates/aws_configuration_template.yml.erb
```

**Comment by drnic** [comment]
Having said that, https://github.com/cloudfoundry/bosh/blob/master/bosh_aws_bootstrap/templates/aws_configuration_template.yml.erb#L8 does not look like it is mentioned in the docs. Do I still need to change anything?

**Comment by drnic** [comment]
https://github.com/cloudfoundry/bosh/commit/78d6415315bf0cbdfac0c6e9ef0b44d121fe6c85

Looks like it might load $BOSH_VPC_DOMAIN now

**Comment by drnic** [comment]
So I guess we can now added `export BOSH_VPC_DOMAIN=my-cloud.com` to `bosh_environment`?

**Comment by drnic** [comment]
With bosh_aws_bootstrap added into the Gemfile, I can now just run:

```
bundle exec bosh aws create
```

**Comment by drnic** [comment]
Hit an error. Raised a ticket. Bed time.

**Comment by drnic** [comment]
Since I'm using HEAD for the aws plugin, I'll try HEAD for the CLI too:

``` ruby
git "git://github.com/cloudfoundry/bosh" do
  gem "bosh_aws_bootstrap"
  gem "bosh_cli"
end
```

**Comment by drnic** [comment]
Nope, still failed.

**Comment by mreider** [comment]
Ok, this was stupid. The instructions would have never worked, so sorry for banging your head. Now we clone bosh into workspace in the instructions. we also changed the environment variables to my-cloud since we support second level domains with the latest bosh.

We will be pushing a new gem when our CI passes, but in the interim we can still use the bundle exec that is in the instructions. WIll remove when the gem is out.
