### ISSUE TITLE
Change "deploy to EC2" to "deploy to AWS VPC"

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf-docs#60]
EC2 and VPC are different; the `bosh_aws_bootstrap` deploys to VPC and cannot deploy to EC2 only

**Comment by mreider** [comment]
I changed the tile and it will show up in the docs when we push tomorrow.

VPC sits on top of EC2. It's not like they are completely different services. When you delete a VPC, for example, it specifically tells you to destroy the EC2 instances that are associated with your VPC. VPC is a set of features that allow EC2 to support subnets.
