### ISSUE TITLE
bundle exec bosh aws create => undefined method `for_sgroup' for Bosh::AwsCloud::ResourceWait:Class

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf-docs#62]
Raised in https://github.com/cloudfoundry/bosh/issues/115 but creating ticket here too as it blocks me from using the VPC tutorial

**Comment by jbayer** [comment]
Nic, https://github.com/cloudfoundry/bosh/issues/115 is now closed, so I'm closing this as well.
