### ISSUE TITLE
 bosh aws create gives error  Access Denied (AWS::S3::Errors::AccessDenied)

### ISSUE THREAD

**Issue by apurvam-haptiq** [cloudfoundry-attic/cf-docs#67]
After "bosh aws create " command I get the  following error:-

/home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:339:in `return_or_raise': Access Denied (AWS::S3::Errors::AccessDenied)
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/gems/aws-sdk-1.8.5/lib/aws/core/client.rb:440:in`client_request'
    from (eval):3:in `get_object'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/gems/aws-sdk-1.8.5/lib/aws/s3/s3_object.rb:1272:in`get_object'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/gems/aws-sdk-1.8.5/lib/aws/s3/s3_object.rb:1058:in `read'
    from /home/ubuntu/workspace/bosh/bosh_cli_plugin_aws/lib/bosh_cli_plugin_aws/s3.rb:51:in`block in fetch_object_contents'
    from /home/ubuntu/workspace/bosh/bosh_common/lib/common/common.rb:65:in `block in retryable'
    from /home/ubuntu/workspace/bosh/bosh_common/lib/common/common.rb:64:in`loop'
    from /home/ubuntu/workspace/bosh/bosh_common/lib/common/common.rb:64:in `retryable'
    from /home/ubuntu/workspace/bosh/bosh_cli_plugin_aws/lib/bosh_cli_plugin_aws/s3.rb:50:in`fetch_object_contents'
    from /home/ubuntu/workspace/bosh/bosh_cli_plugin_aws/lib/bosh_cli_plugin_aws/migrator.rb:81:in `load_migrations_for_env'
    from /home/ubuntu/workspace/bosh/bosh_cli_plugin_aws/lib/bosh_cli_plugin_aws/migrator.rb:35:in`environment_migrations'
    from /home/ubuntu/workspace/bosh/bosh_cli_plugin_aws/lib/bosh_cli_plugin_aws/migrator.rb:40:in `needs_migration?'
    from /home/ubuntu/workspace/bosh/bosh_cli_plugin_aws/lib/bosh_cli_plugin_aws/migrator.rb:11:in`migrate'
    from /home/ubuntu/workspace/bosh/bosh_cli_plugin_aws/lib/bosh/cli/commands/aws.rb:145:in `create'
    from /home/ubuntu/workspace/bosh/bosh_cli/lib/cli/command_handler.rb:57:in`run'
    from /home/ubuntu/workspace/bosh/bosh_cli/lib/cli/runner.rb:59:in `run'
    from /home/ubuntu/workspace/bosh/bosh_cli/lib/cli/runner.rb:18:in`run'
    from /home/ubuntu/workspace/bosh/bosh_cli/bin/bosh:7:in `<top (required)>'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/bin/bosh:19:in`load'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/bin/bosh:19:in `<main>'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/bin/ruby_noexec_wrapper:14:in`eval'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p327@bosh/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by mreider** [comment]
This page, as it says at the top, will not work as intended for at least a few weeks.
