### ISSUE TITLE
documentation issue: v2 + vmc?

### ISSUE THREAD

**Issue by halfbaked** [cloudfoundry-attic/cf-docs#78]
I'm reading about deploying CF with on BOSH on AWS (all the acronyms!).
It's here: http://docs.cloudfoundry.com/docs/running/deploying-cf/ec2/index.html

It describes using vmc and how they are V2 docs. If I understand right, those two seem to be mutually exclusive as vmc is deprecated in favor of cf in v2.

**Comment by scottfrederick** [comment]
Good catch. I'm making some updates to other docs now, I will fix that while I'm at it.

**Comment by scottfrederick** [comment]
https://github.com/cloudfoundry/cf-docs/pull/79
