### ISSUE TITLE
checking cloudfoundry version

### ISSUE THREAD

**Issue by Remo** [cloudfoundry-attic/cf-docs#89]
Not sure if this is a documentation issue but I find it a bit tricky to check the cloud foundry version. On this page http://docs.cloudfoundry.com/docs/dotcom/integration/cloudbees/ you write that we can use a url like this to check the version:

http://api.cloudfoundry.com/info

I get some information but it's a complete json object and pretty hard to understand. You might want to explain that with a few more details in the documentation.

**Comment by jbayer** [comment]
This is addressed by https://github.com/cloudfoundry/cf-docs/pull/90
